### ISSUE TITLE
scheduled notification in the queue is not saved

### ISSUE THREAD

**Issue by StevenArmandLee** [ahmedabadie/ABNScheduler#13]
the notification in the queue is not saved when we close and open the app again

**Comment by ahmdx** [comment]
Are you using it for Swift 3 or Swift 2.2?

Also, did you call `ABNScheduler.saveQueue()`?

**Comment by StevenArmandLee** [comment]
yes I did call save queue every time I schedule a new one. I just added the savequeque in your schedule function

both 3 and 2.2 is not working

**Comment by ahmdx** [comment]
What version of iOS did you test it on?

**Comment by StevenArmandLee** [comment]
10.2

10.1 is also the same.

is it because i was testing using emultor?

**Comment by StevenArmandLee** [comment]
I tried on real device, still the same. the queue is empty every time i close and open the app

**Comment by ahmdx** [comment]
I have tried it on both a real device and simulators and it does not load the queue from disk on iOS 9.3+.

ABNScheduler uses NSKeyedArchiver to store and retrieve the notification queue. I have observed something weird while trying to figure out what was going on. The `Bool` data type is either not properly saved or read from disk, which causes the ABNQueue to fail loading the notifications. This also happens with the `Int` data type. Not sure about all the other data types.

I just have to make sure that this is a bug from Apple's side not from anything in the current implementation and then push the fixes.

If you need a quick workaround, just don't decode the `ABNScheduled` key in `init?(coder aDecoder: NSCoder)` and pass `false` to the initializer instead of the decoded variable and set a default value to the `soundName` attribute in `ABNotification`.

**Comment by StevenArmandLee** [comment]
well I'm not sure if it is bug from iOS itself. but yeah just tell me when you figure it out. I will help to figure it out in my free time.

cheers :) good to see that this repo is back to be active

**Comment by ahmdx** [comment]
The library now should save and load the queue correctly. Happy holidays :)

**Comment by StevenArmandLee** [comment]
@ahmedabadie ok cool, I will test it soon.

**Comment by Narasimha4** [comment]
Hi @ahmedabadie Thanks for this project.
I have some issues while running in devices, if i run in simulator its triggering and working properly.
If i am running in devices some iphone devices its working and some of them devices its getting crashed. due to its showing **identifier nil**.
Help me out, i was helpless.

**Comment by Narasimha4** [comment]
@ahmedabadie  
Hii its getting crashed and saying that identifier is nil while running project in device.

**Comment by ahmdx** [comment]
Would you please specify where this error happens and what are the stack contents?
